version: "3.7"

services:
  db:
    build: ./db
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  webapp:
    build: ./webapp
    ports:
      - 8080:80
    env_file:
      - ./webapp/.env
    depends_on:
      - api

volumes:
  postgres_data:
