# Generated by Django 3.1.7 on 2021-02-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='assigned_to',
        ),
    ]
