# Generated by Django 3.1.7 on 2021-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0002_remove_hit_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='description',
            field=models.CharField(default='Default Value', max_length=200),
            preserve_default=False,
        ),
    ]
