# Generated by Django 3.1.6 on 2021-02-22 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('type', models.CharField(choices=[('boss', 'boss'), ('manager', 'manager'), ('hitman', 'hitman')], default='hitman', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitmen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hitmen',
                'ordering': ['created_at', 'updated_at'],
            },
        ),
    ]
